# --- MIXRTs specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000 # 500000 for 6h_vs_8z

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "mixrts_learner"
double_q: True

agent: "rtcs" # Default rnn agent
rnn_hidden_dim: 32 # Size of hidden state for default rtrs agent
q_tree_depth: 3
mixer: "mixrts"
mixing_embed_dim: 16
mix_q_tree_depth: 3

kernel: "dot" # dot/add
softmax_w: True
beta: 0
burn_in_period: 100
td_lambda: 0.6

name: "mixrts"
