# --- Qatten specific parameters ---


# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200


obs_agent_id: False
obs_last_action: False
obs_individual_obs: False


# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True

agent_output_type: "q"
learner: "qamix_learner"
double_q: True
mixer: "qatten"
use_rnn: True
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
agent: "transformer"


n_query_embedding_layer1: 64
n_query_embedding_layer2: 32
n_key_embedding_layer1: 32
n_head_embedding_layer1: 64
n_head_embedding_layer2: 4
n_attention_head: 4
n_constrant_value: 32
type: "weighted"
agent_own_state_size: True

name: "qamix-e"

