# --- Diffusion Q specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000  # 6h_vs_8z=100000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

agent: "rnn_sd" # Default rnn agent
rnn_hidden_dim: 64 # Default rnn_hidden_dim=vae_latent_dim

# use the Q_Learner to train
agent_output_type: "q"
learner: "qnam_learner"
double_q: True
mixer: "qnam"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
obs_agent_id: False # Include the agent's one_hot id in the observation
burn_in_period: 100
mix_nary: [1, 2]  # mix nam n-ary
beta_vae: 0.1 # vae latent loss beta

name: "qnam"
